import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'YooMovies',
  description: 'Generated by create next app',
  icons: {
    icon: '/YM.png?v=4', 
    apple: ['/YM.png?v=4'], 
    shortcut: ['/YM.png'], 
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
